name: Python build and test
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deta Space CLI
        run: curl -fsSL https://deta.space/assets/space-cli.sh | sh
      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install project (incl. dev) dependencies
        run: |
          pipenv install --dev
      - name: Test with pytest
        env:
          DETA_SPACE_DATA_KEY: ${{ secrets.DETA_SPACE_DATA_KEY }}
        run: pipenv run pytest
      - name: Push working code to Deta Space
        env:
          DETA_SPACE_TOKEN: ${{ secrets.DETA_SPACE_TOKEN }}
        run: |
          space login --with_token <<<"$DETA_SPACE_TOKEN"
          space push
